# src/formatter.py

from datetime import datetime
from config import SUMMARY_LANGUAGE

TOPIC_LABELS = {
    "agents":     "Agents & open source",
    "models":     "New models",
    "tools":      "Dev tools & MLOps",
    "industry":   "AI in the wild",
    "research":   "Research & papers",
    "regulation": "Regulation & ethics",
}

TOPIC_ICONS = {
    "agents":     "🤖",
    "models":     "🧠",
    "tools":      "⚙️",
    "industry":   "🏭",
    "research":   "📄",
    "regulation": "⚖️",
}


def build_email(digest: dict[str, list]) -> tuple[str, str]:
    date_str  = datetime.now().strftime("%A %d %B %Y")
    total     = sum(len(v) for v in digest.values())
    subject   = f"AI Brief — {date_str} — {total} things worth knowing"
    html      = _build_html(digest, date_str, total)
    return subject, html


def _build_html(digest: dict, date_str: str, total: int) -> str:
    sections = ""
    for topic, items in digest.items():
        if not items:
            continue
        label = TOPIC_LABELS.get(topic, topic)
        icon  = TOPIC_ICONS.get(topic, "•")
        cards = ""
        for item in items:
            source_badge = f'<span style="background:#f0f0f0;padding:2px 8px;border-radius:12px;font-size:12px;color:#666">{item["source"]}</span>'
            type_badge   = f'<span style="background:#e8f4fd;padding:2px 8px;border-radius:12px;font-size:12px;color:#1a73e8;margin-left:6px">{item["type"]}</span>'
            stars        = f'<span style="margin-left:8px;font-size:12px;color:#f4a100">★ {item["stars"]:,}</span>' if item.get("stars") else ""
            cards += f"""
            <div style="border:1px solid #eee;border-radius:10px;padding:16px 20px;margin-bottom:12px;background:#fff">
                <div style="margin-bottom:8px">{source_badge}{type_badge}{stars}</div>
                <a href="{item['url']}" style="font-size:16px;font-weight:600;color:#111;text-decoration:none;line-height:1.4">
                    {item['title']}
                </a>
                <p style="margin:10px 0 0;font-size:14px;color:#444;line-height:1.6">
                    {item.get('ai_summary') or item.get('summary','')[:200]}
                </p>
            </div>"""

        sections += f"""
        <div style="margin-bottom:32px">
            <h2 style="font-size:18px;font-weight:700;color:#111;margin:0 0 14px;padding-bottom:8px;border-bottom:2px solid #f0f0f0">
                {icon} {label}
            </h2>
            {cards}
        </div>"""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f6f6f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
    <div style="max-width:640px;margin:0 auto;padding:24px 16px">

        <div style="background:#111;border-radius:14px;padding:28px 32px;margin-bottom:24px">
            <div style="font-size:12px;color:#888;letter-spacing:1px;text-transform:uppercase;margin-bottom:6px">
                Daily digest
            </div>
            <h1 style="margin:0;font-size:26px;font-weight:700;color:#fff">
                AI Brief
            </h1>
            <div style="margin-top:8px;font-size:14px;color:#aaa">
                {date_str} &nbsp;·&nbsp; {total} items
            </div>
        </div>

        {sections}

        <div style="text-align:center;padding:24px 0;font-size:12px;color:#aaa">
            Generated by ai-brief &nbsp;·&nbsp;
            <a href="https://github.com/ton-username/ai-brief" style="color:#aaa">GitHub</a>
        </div>

    </div>
</body>
</html>"""